Repository Snailclimb/JavaGuide, pull requests merged in 2020-10, with the labels that each got.

#946 Fix typo
  docs/system-design/framework/spring/SpringInterviewQuestions.md
Labels: typo

#947 Update JVM垃圾回收.md
  docs/java/jvm/JVM垃圾回收.md
Labels: enhancement

#948 fix: 规范 MyBatis 大小写
  docs/system-design/framework/mybatis/mybatis-interview.md
Labels: typo

#955 fix markdown error
  docs/java/basis/Java基础知识.md
Labels: typo

#956 Fix URL and Content errors
  docs/java/basis/Java基础知识.md
Labels: typo

#960 fix
  docs/java/jvm/类加载过程.md
Labels: bug

#962 修改错别字：事物 -> 事务
  docs/database/MySQL.md
Labels: typo
