Repository Snailclimb/JavaGuide, pull requests merged in 2020-11, with the labels that each got.

#977 Update limit-request.md
  docs/system-design/high-availability/limit-request.md
Labels: enhancement

#985 Update ArrayList源码+扩容机制分析.md
  docs/java/collection/ArrayList源码+扩容机制分析.md
Labels: typo

#986 Update basis-of-authority-certification.md
  docs/system-design/authority-certification/basis-of-authority-certification.md
Labels: typo

#994 Update JVM垃圾回收.md
  docs/java/jvm/JVM垃圾回收.md
  docs/java/jvm/类加载过程.md
  docs/java/jvm/类文件结构.md
Labels: bug, enhancement

#996 fix typo
  docs/essential-content-for-interview/PreparingForInterview/美团面试常见问题总结.md
  docs/system-design/framework/spring/Spring事务总结.md
Labels: typo

#998 fix markdown error
  docs/java/basis/BIO,NIO,AIO总结.md
Labels: typo

#999 fix markdown error
  docs/java/basis/BIO,NIO,AIO总结.md
Labels: typo

#1001 修改错别字
  docs/java/basis/BIO,NIO,AIO总结.md
Labels: typo
