Repository Snailclimb/JavaGuide, pull requests merged in 2021-07, with the labels that each got.

#1277 修正错字
  docs/system-design/distributed-system/zookeeper/zookeeper-intro.md
Labels: typo

#1281 错别字修改
  docs/network/计算机网络.md
Labels: typo

#1278 增加zookeeper选举的过半机制防止脑裂的描述
  docs/system-design/distributed-system/zookeeper/zookeeper-intro.md
Labels: awesome, enhancement

#1286 Update CAP理论.md
  docs/system-design/distributed-system/CAP理论.md
Labels: typo

#1297 Update zookeeper-intro.md
  docs/system-design/distributed-system/zookeeper/zookeeper-intro.md
Labels: enhancement
