Repository Snailclimb/JavaGuide, pull requests merged in 2022-10, with the labels that each got.

#1839 修改了 “Java8 新特性 Date-Time API 格式化” 示例代码的注释
  docs/java/new-features/java8-common-new-features.md
Labels: typo

#1842 完善对TCP报文首部长度的描述
  docs/cs-basics/network/computer-network-xiexiren-summary.md
Labels: bug

#1845 Update why-there-only-value-passing-in-java.md
  docs/java/basis/why-there-only-value-passing-in-java.md
Labels: enhancement
